# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansible_Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=50, unique=True, verbose_name='剧本名称')),
                ('playbook_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='功能描述')),
                ('playbook_vars', models.TextField(blank=True, null=True, verbose_name='模块参数')),
                ('playbook_uuid', models.CharField(max_length=50, verbose_name='唯一id')),
                ('playbook_file', models.FileField(upload_to='./upload/playbook/', verbose_name='剧本路径')),
                ('playbook_auth_group', models.SmallIntegerField(blank=True, null=True, verbose_name='授权组')),
                ('playbook_auth_user', models.SmallIntegerField(blank=True, null=True, verbose_name='授权用户')),
            ],
            options={
                'verbose_name': 'Ansible剧本配置表',
                'db_table': 'opssystem_ansible_playbook',
                'permissions': (('can_read_ansible_playbook', '读取Ansible剧本权限'), ('can_change_ansible_playbook', '更改Ansible剧本权限'), ('can_add_ansible_playbook', '添加Ansible剧本权限'), ('can_delete_ansible_playbook', '删除Ansible剧本权限')),
                'verbose_name_plural': 'Ansible剧本配置表',
            },
        ),
        migrations.CreateModel(
            name='Ansible_Playbook_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_server', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标服务器')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_number', to='appdeploy.Ansible_Playbook')),
            ],
            options={
                'verbose_name': 'Ansible剧本成员表',
                'db_table': 'opssystem_ansible_playbook_number',
                'permissions': (('can_read_ansible_playbook_number', '读取Ansible剧本成员权限'), ('can_change_ansible_playbook_number', '更改Ansible剧本成员权限'), ('can_add_ansible_playbook_number', '添加Ansible剧本成员权限'), ('can_delete_ansible_playbook_number', '删除Ansible剧本成员权限')),
                'verbose_name_plural': 'Ansible剧本成员表',
            },
        ),
        migrations.CreateModel(
            name='Log_Ansible_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_user', models.CharField(default=None, max_length=50, verbose_name='使用用户')),
                ('ans_model', models.CharField(default=None, max_length=100, verbose_name='模块名称')),
                ('ans_args', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='模块参数')),
                ('ans_server', models.TextField(default=None, verbose_name='服务器')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'Ansible模块执行记录表',
                'db_table': 'opssystem_log_ansible_model',
                'permissions': (('can_read_log_ansible_model', '读取Ansible模块执行记录权限'), ('can_change_log_ansible_model', '更改Ansible模块执行记录权限'), ('can_add_log_ansible_model', '添加Ansible模块执行记录权限'), ('can_delete_log_ansible_model', '删除Ansible模块执行记录权限')),
                'verbose_name_plural': 'Ansible模块执行记录表',
            },
        ),
        migrations.CreateModel(
            name='Log_Ansible_Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='id')),
                ('ans_user', models.CharField(default=None, max_length=50, verbose_name='使用用户')),
                ('ans_name', models.CharField(default=None, max_length=100, verbose_name='模块名称')),
                ('ans_content', models.CharField(default=None, max_length=100)),
                ('ans_server', models.TextField(default=None, verbose_name='服务器')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'Ansible剧本操作记录表',
                'db_table': 'opssystem_log_ansible_playbook',
                'verbose_name_plural': 'Ansible剧本操作记录表',
            },
        ),
    ]
