# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Project_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='资产类型id')),
                ('project_user', models.CharField(default=None, max_length=50, verbose_name='操作用户')),
                ('project_name', models.CharField(default=None, max_length=100, verbose_name='名称')),
                ('project_content', models.CharField(default=None, max_length=100)),
                ('project_branch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '项目配置操作记录表',
                'db_table': 'opssystem_log_project_config',
                'verbose_name_plural': '项目配置操作记录表',
            },
        ),
        migrations.CreateModel(
            name='Project_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_env', models.CharField(default=None, max_length=50, verbose_name='项目环境')),
                ('project_name', models.CharField(default=None, max_length=100, verbose_name='项目名称')),
                ('project_local_command', models.TextField(blank=True, default=None, null=True, verbose_name='部署服务器要执行的命令')),
                ('project_repo_dir', models.CharField(default=None, max_length=100, verbose_name='本地仓库目录')),
                ('project_dir', models.CharField(default=None, max_length=100, verbose_name='代码目录')),
                ('project_exclude', models.TextField(blank=True, default=None, null=True, verbose_name='排除文件')),
                ('project_address', models.CharField(default=None, max_length=100, verbose_name='版本仓库地址')),
                ('project_uuid', models.CharField(max_length=50, verbose_name='唯一id')),
                ('project_repo_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库用户名')),
                ('project_repo_passwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库密码')),
                ('project_repertory', models.CharField(choices=[('git', 'git'), ('svn', 'svn')], default=None, max_length=10, verbose_name='仓库类型')),
                ('project_status', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='是否激活')),
                ('project_remote_command', models.TextField(blank=True, default=None, null=True, verbose_name='部署之后执行的命令')),
                ('project_user', models.CharField(default=None, max_length=50, verbose_name='项目文件宿主')),
                ('project_model', models.CharField(choices=[('branch', 'branch'), ('tag', 'tag')], default=None, max_length=10, verbose_name='上线类型')),
                ('project_audit_group', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='项目授权组')),
            ],
            options={
                'verbose_name': '项目管理表',
                'db_table': 'opssystem_project_config',
                'permissions': (('can_read_project_config', '读取项目权限'), ('can_change_project_config', '更改项目权限'), ('can_add_project_config', '添加项目权限'), ('can_delete_project_config', '删除项目权限')),
                'verbose_name_plural': '项目管理表',
            },
        ),
        migrations.CreateModel(
            name='Project_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default=None, max_length=100, verbose_name='服务器IP')),
                ('dir', models.CharField(default=None, max_length=100, verbose_name='项目目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_number', to='codedeploy.Project_Config')),
            ],
            options={
                'verbose_name': '项目成员表',
                'db_table': 'opssystem_project_number',
                'permissions': (('can_read_project_number', '读取项目成员权限'), ('can_change_project_number', '更改项目成员权限'), ('can_add_project_number', '添加项目成员权限'), ('can_delete_project_number', '删除项目成员权限')),
                'verbose_name_plural': '项目成员表',
            },
        ),
        migrations.CreateModel(
            name='Project_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_user', models.CharField(max_length=30, verbose_name='工单申请人')),
                ('order_subject', models.CharField(max_length=200, verbose_name='工单申请主题')),
                ('order_content', models.TextField(verbose_name='工单申请内容')),
                ('order_branch', models.CharField(blank=True, max_length=50, null=True, verbose_name='分支版本')),
                ('order_comid', models.CharField(blank=True, max_length=100, null=True, verbose_name='版本id')),
                ('order_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('order_audit', models.CharField(max_length=30, verbose_name='部署指派人')),
                ('order_status', models.IntegerField(choices=[(0, '已通过'), (1, '已拒绝'), (2, '审核中'), (3, '已部署')], default='审核中', verbose_name='工单状态')),
                ('order_level', models.IntegerField(choices=[(0, '非紧急'), (1, '紧急')], default='非紧急', verbose_name='工单紧急程度')),
                ('order_cancel', models.TextField(blank=True, null=True, verbose_name='取消原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单发布时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='工单最后修改时间')),
                ('order_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codedeploy.Project_Config', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '项目部署工单表',
                'db_table': 'opssystem_project_order',
                'permissions': (('can_read_project_order', '读取项目部署权限'), ('can_change_project_order', '更改项目部署权限'), ('can_add_project_order', '添加项目部署权限'), ('can_delete_project_order', '删除项目部署权限')),
                'verbose_name_plural': '项目部署工单表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='project_config',
            unique_together=set([('project_env', 'project_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='project_order',
            unique_together=set([('order_project', 'order_subject', 'order_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='project_number',
            unique_together=set([('project', 'server')]),
        ),
    ]
